import type { Roadmap, Achievement } from './types';

export const sampleRoadmap: Roadmap = {
  id: 'frontend-mastery',
  title: 'Frontend Mastery Roadmap',
  description: 'A comprehensive roadmap to master frontend development',
  nodes: [
    {
      id: 'start',
      title: 'Getting Started',
      description: 'Learn the basics of web development',
      type: 'milestone',
      status: 'available',
      position: { x: 50, y: 300 },
      dependencies: [],
      estimatedTime: '2 weeks',
      resources: [
        { type: 'article', title: 'How the Web Works', url: '#' },
        { type: 'video', title: 'HTML & CSS Basics', url: '#' },
      ],
      rewards: [{ type: 'xp', value: 100 }],
    },
    {
      id: 'html-css',
      title: 'HTML & CSS',
      description: 'Master the building blocks of the web',
      type: 'task',
      status: 'locked',
      position: { x: 250, y: 200 },
      dependencies: ['start'],
      estimatedTime: '3 weeks',
      resources: [
        { type: 'article', title: 'Semantic HTML Guide', url: '#' },
        { type: 'tool', title: 'CSS Flexbox Playground', url: '#' },
      ],
      rewards: [{ type: 'xp', value: 200 }, { type: 'badge', value: 'HTML Master' }],
    },
    {
      id: 'javascript',
      title: 'JavaScript Fundamentals',
      description: 'Learn the language of the web',
      type: 'task',
      status: 'locked',
      position: { x: 250, y: 400 },
      dependencies: ['start'],
      estimatedTime: '4 weeks',
      resources: [
        { type: 'video', title: 'JS Basics Course', url: '#' },
        { type: 'article', title: 'ES6+ Features', url: '#' },
      ],
      rewards: [{ type: 'xp', value: 300 }, { type: 'badge', value: 'JS Ninja' }],
    },
    {
      id: 'react-basics',
      title: 'React Basics',
      description: 'Introduction to React framework',
      type: 'task',
      status: 'locked',
      position: { x: 450, y: 300 },
      dependencies: ['html-css', 'javascript'],
      estimatedTime: '3 weeks',
      resources: [
        { type: 'video', title: 'React Official Tutorial', url: '#' },
        { type: 'tool', title: 'React DevTools', url: '#' },
      ],
      rewards: [{ type: 'xp', value: 400 }, { type: 'badge', value: 'React Rookie' }],
    },
    {
      id: 'typescript',
      title: 'TypeScript',
      description: 'Add type safety to your code',
      type: 'challenge',
      status: 'locked',
      position: { x: 450, y: 500 },
      dependencies: ['javascript'],
      estimatedTime: '2 weeks',
      resources: [
        { type: 'article', title: 'TS Handbook', url: '#' },
        { type: 'tool', title: 'TS Playground', url: '#' },
      ],
      rewards: [{ type: 'xp', value: 350 }, { type: 'badge', value: 'Type Master' }],
    },
    {
      id: 'advanced-react',
      title: 'Advanced React',
      description: 'Hooks, Context, and Performance',
      type: 'challenge',
      status: 'locked',
      position: { x: 650, y: 300 },
      dependencies: ['react-basics', 'typescript'],
      estimatedTime: '4 weeks',
      resources: [
        { type: 'video', title: 'Advanced Patterns', url: '#' },
        { type: 'article', title: 'Performance Optimization', url: '#' },
      ],
      rewards: [
        { type: 'xp', value: 500 },
        { type: 'badge', value: 'React Expert' },
        { type: 'title', value: 'Senior Developer' },
      ],
    },
    {
      id: 'nextjs',
      title: 'Next.js',
      description: 'Full-stack React framework',
      type: 'task',
      status: 'locked',
      position: { x: 650, y: 100 },
      dependencies: ['react-basics'],
      estimatedTime: '3 weeks',
      resources: [
        { type: 'article', title: 'Next.js Docs', url: '#' },
        { type: 'video', title: 'App Router Guide', url: '#' },
      ],
      rewards: [{ type: 'xp', value: 450 }, { type: 'badge', value: 'Next.js Pro' }],
    },
    {
      id: 'testing',
      title: 'Testing',
      description: 'Unit and integration testing',
      type: 'challenge',
      status: 'locked',
      position: { x: 850, y: 400 },
      dependencies: ['advanced-react'],
      estimatedTime: '2 weeks',
      resources: [
        { type: 'article', title: 'Testing Best Practices', url: '#' },
        { type: 'tool', title: 'Jest & React Testing Library', url: '#' },
      ],
      rewards: [{ type: 'xp', value: 400 }, { type: 'badge', value: 'Test Master' }],
    },
    {
      id: 'deployment',
      title: 'Deployment',
      description: 'Deploy your applications',
      type: 'milestone',
      status: 'locked',
      position: { x: 1050, y: 250 },
      dependencies: ['nextjs', 'advanced-react', 'testing'],
      estimatedTime: '1 week',
      resources: [
        { type: 'article', title: 'Vercel Deployment', url: '#' },
        { type: 'video', title: 'CI/CD Pipeline', url: '#' },
      ],
      rewards: [
        { type: 'xp', value: 600 },
        { type: 'badge', value: 'Ship It!' },
        { type: 'title', value: 'Full Stack Developer' },
      ],
    },
    {
      id: 'bonus-optimization',
      title: 'Performance Optimization',
      description: 'Make your apps blazing fast',
      type: 'challenge',
      status: 'locked',
      position: { x: 850, y: 100 },
      dependencies: ['nextjs'],
      branch: 'advanced',
      estimatedTime: '2 weeks',
      resources: [
        { type: 'article', title: 'Core Web Vitals', url: '#' },
        { type: 'tool', title: 'Lighthouse', url: '#' },
      ],
      rewards: [{ type: 'xp', value: 500 }, { type: 'badge', value: 'Speed Demon' }],
    },
  ],
  branches: [
    {
      id: 'main',
      name: 'Main Path',
      description: 'The core learning path',
      color: 'var(--primary)',
      nodes: ['start', 'html-css', 'javascript', 'react-basics', 'advanced-react', 'deployment'],
    },
    {
      id: 'advanced',
      name: 'Advanced Track',
      description: 'For experienced developers',
      color: 'var(--warning)',
      nodes: ['bonus-optimization'],
      requiredLevel: 5,
    },
  ],
  connections: [
    { from: 'start', to: 'html-css', type: 'required' },
    { from: 'start', to: 'javascript', type: 'required' },
    { from: 'html-css', to: 'react-basics', type: 'required' },
    { from: 'javascript', to: 'react-basics', type: 'required' },
    { from: 'javascript', to: 'typescript', type: 'optional' },
    { from: 'react-basics', to: 'advanced-react', type: 'required' },
    { from: 'typescript', to: 'advanced-react', type: 'required' },
    { from: 'react-basics', to: 'nextjs', type: 'optional' },
    { from: 'advanced-react', to: 'testing', type: 'optional' },
    { from: 'nextjs', to: 'deployment', type: 'required' },
    { from: 'advanced-react', to: 'deployment', type: 'required' },
    { from: 'testing', to: 'deployment', type: 'required' },
    { from: 'nextjs', to: 'bonus-optimization', type: 'branch' },
  ],
};

export const sampleAchievements: Achievement[] = [
  {
    id: 'first-steps',
    name: 'First Steps',
    description: 'Complete your first node in the roadmap',
    type: 'progress',
    rarity: 'common',
    icon: '[FS]',
    condition: { type: 'complete_nodes', value: 1 },
    rewards: [{ type: 'xp', value: 50 }],
  },
  {
    id: 'getting-started',
    name: 'Getting Started',
    description: 'Complete 3 nodes in the roadmap',
    type: 'progress',
    rarity: 'common',
    icon: '[GS]',
    condition: { type: 'complete_nodes', value: 3 },
    rewards: [{ type: 'xp', value: 100 }, { type: 'badge', value: 'Beginner' }],
  },
  {
    id: 'roadmap-warrior',
    name: 'Roadmap Warrior',
    description: 'Complete 10 nodes in the roadmap',
    type: 'progress',
    rarity: 'rare',
    icon: '[RW]',
    condition: { type: 'complete_nodes', value: 10 },
    rewards: [{ type: 'xp', value: 300 }, { type: 'badge', value: 'Warrior' }],
  },
  {
    id: 'master-developer',
    name: 'Master Developer',
    description: 'Complete all nodes in the main branch',
    type: 'challenge',
    rarity: 'epic',
    icon: '[MD]',
    condition: { type: 'complete_branch', target: 'main' },
    rewards: [
      { type: 'xp', value: 1000 },
      { type: 'badge', value: 'Master Developer' },
      { type: 'title', value: 'Frontend Master' },
    ],
  },
  {
    id: 'speed-runner',
    name: 'Speed Runner',
    description: 'Complete 5 nodes in a single day',
    type: 'challenge',
    rarity: 'rare',
    icon: '[SR]',
    condition: {
      type: 'custom',
      customCheck: (state) => state.completedNodes.length >= 5,
    },
    rewards: [{ type: 'xp', value: 500 }, { type: 'badge', value: 'Speedster' }],
  },
  {
    id: 'dedicated-learner',
    name: 'Dedicated Learner',
    description: 'Maintain a 7-day learning streak',
    type: 'progress',
    rarity: 'epic',
    icon: '[DL]',
    condition: { type: 'streak', value: 7 },
    rewards: [{ type: 'xp', value: 700 }, { type: 'badge', value: 'Dedicated' }],
  },
  {
    id: 'typescript-ninja',
    name: 'TypeScript Ninja',
    description: 'Complete the TypeScript challenge node',
    type: 'challenge',
    rarity: 'rare',
    icon: '[TN]',
    condition: { type: 'complete_nodes', target: 'typescript' },
    rewards: [{ type: 'xp', value: 400 }, { type: 'badge', value: 'TS Ninja' }],
  },
  {
    id: 'react-expert',
    name: 'React Expert',
    description: 'Complete all React-related nodes',
    type: 'challenge',
    rarity: 'epic',
    icon: '[RE]',
    condition: {
      type: 'custom',
      customCheck: (state) =>
        ['react-basics', 'advanced-react'].every((id) =>
          state.completedNodes.includes(id)
        ),
    },
    rewards: [{ type: 'xp', value: 800 }, { type: 'badge', value: 'React Expert' }],
  },
  {
    id: 'legendary-coder',
    name: 'Legendary Coder',
    description: 'Unlock all achievements',
    type: 'special',
    rarity: 'legendary',
    icon: '[LC]',
    condition: {
      type: 'custom',
      customCheck: (state) => state.achievements.length >= 8,
    },
    rewards: [
      { type: 'xp', value: 5000 },
      { type: 'badge', value: 'Legend' },
      { type: 'title', value: 'Coding Legend' },
    ],
  },
  {
    id: 'secret-achievement',
    name: 'Secret Achievement',
    description: 'You found a hidden achievement!',
    type: 'hidden',
    rarity: 'legendary',
    icon: '[SA]',
    condition: {
      type: 'custom',
      customCheck: (state) => state.completedNodes.length >= 5,
    },
    isHidden: true,
    hint: 'Keep completing nodes to unlock this secret...',
    rewards: [{ type: 'xp', value: 1000 }, { type: 'item', value: 'Mystery Box' }],
  },
];
